//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculatorHistory
    {
        public int Id { get; set; }
        public string MathExpression { get; set; }
        public int Result { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
