//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Units
    {
        public Units()
        {
            this.Employees = new HashSet<Employees>();
        }
    
        public int Id_Unit { get; set; }
        public string Unit { get; set; }
    
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
